#!/bin/sh
# Usage: script/boostrap
# Ensures all dependencies are installed locally.

set -e
cd "$(dirname "$0")/.."

echo "==> Installing gem dependencies…"
bundle install --without production

echo "==> Installing node dependencies…"
yarn install
