#!/bin/sh

# script/cibuild: Setup environment for CI to run tests. This is primarily
#                 designed to run on the continuous integration server.

set -e

cd "$(dirname "$0")/.."

# run tests
echo "Running tests ..."
date "+%H:%M:%S"

case $TEST_SUITE in
  rspec)
    psql -c 'create database classroom_test;' -U postgres
    bundle exec rake db:migrate
    bundle exec rspec
    ;;
  linters)
    script/linter
    ;;
  *) echo 'TEST_SUITE not set' ;;
esac
